### ISSUE TITLE
some data issues

### ISSUE THREAD

**Issue by duanmu3** [richardbeare/ipa_illustrations#2]
Hello,

I found a few minor issues in the 'Illustrations of the IPA' website:
1. Five 'Brunei Malay' names are listed but only 4 pointers are on the map
2. When 'Cocos Malay' is clicked, it does not show up on the map.
3. Two 'Telugu' names seem to have the same PDF file.
4. 'Tukang Besi' has no audio file

Thanks,
San

**Comment by richardbeare** [comment]
Thanks for pointing this out, I'll work on fixes.

1. Brunei Malay - I think the issue here is there are two languages (standard and Brunei Malay) with the same location, so the pins are over the top of each other. I'll need to tweak the locations so both are visible.

1. Cocos Malay - same issue. There are several languages listed as being spoken in "Sabah, Malaysia", so the pins have been stuck on top of each other.

1. The two "Telugu" names are referencing the same publication. The locations come from the illustration abstract, and often there are several listed. The asterix after the  language name on the pin popup is meant to indicate that there is at least one other pin related to the same publication. Not ideal, but best option I could think of.

1. 'Tukang Besi' is from the handbook (green pin). Will ask the experts whether there is a recording.

**Comment by duanmu3** [comment]
I see. Thank you for your reply!

San

**Comment by richardbeare** [comment]
Hi,
I've implemented a jitter so that those overlapping pins are visible. The jitter is small, so sometimes it is necessary to zoom in. 

I checked the status of 'Tukang Besi' recordings and confirmed that there isn't one, unfortunately.

**Comment by duanmu3** [comment]
OK, tThank you again!


San


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
