### ISSUE TITLE
Palula

### ISSUE THREAD

**Issue by aryamanarora** [richardbeare/ipa_illustrations#5]
If I'm not mistaken, Palula is missing from the map (JIPA article: https://doi.org/10.1017/S0025100309990193).

**Comment by aryamanarora** [comment]
Interestingly, when I click the link for Palula among the languages listed, it zooms into Kalasha (Bumburet variety).

**Comment by richardbeare** [comment]
Hi,
Thanks for the report. It turns out that there are two languages from adjacent provinces that are marked on the map (Palula and Kalasha). These are very close together and appear overlapped on a zoomed out view. They will separate if you zoom in, making Palula visible.

I will add a note to the introductory section to alert users to this potential problem.

Thanks again

**Comment by aryamanarora** [comment]
Great, thank you so much!
